services:
  php:
    build: ./php
    volumes:
      - ./tataplay:/var/www/html
    networks:
      - app-network

  apache:
    image: php:8.1-apache
    volumes:
      - ./tataplay:/var/www/html
      - ./apache/apache.conf:/etc/apache2/sites-available/000-default.conf # Custom Apache config
    ports:
      - "8181:80"
    depends_on:
      - php
    networks:
      - app-network
    command: >
      sh -c "a2enmod rewrite && apache2-foreground" # Enable mod_rewrite for .htaccess support

networks:
  app-network:
    driver: bridge
