services:
  php:
    build: ./php
    volumes:
      - ./tataplay:/var/www/html
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    volumes:
      - ./tataplay:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - php
    networks:
      - app-network

networks:
  app-network:
    driver: bridge